# Generated by Django 3.2.7 on 2021-10-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211002_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qid',
        ),
    ]
