# Generated by Django 3.2.7 on 2021-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_question_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.CharField(default='abcdxyz', max_length=200),
            preserve_default=False,
        ),
    ]
