# Generated by Django 3.2.7 on 2021-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='roomname',
            field=models.CharField(default='no room', max_length=200),
        ),
    ]
