# Generated by Django 3.2.7 on 2021-10-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resource_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
